version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: circuithub_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samir
      POSTGRES_DB: circuithub
    ports:
      - "5432:5432"
    volumes:
      - circuithub_pgdata:/var/lib/postgresql/data

volumes:
  circuithub_pgdata:
